### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by OrionRandD** [raniaamina/LibreOffice-Content-Generator#2]
Just a suggestion.
Is there a way to design a button in the tool-bar to run the plugin?
Too many clicks to run it and get the answer   :(

**Comment by iradraconis** [comment]
Please select Extras -> Customize from the menu bar.

Scroll down and select Context Menus.

Scroll down the category and select Macros.

Choose the macro from the list and click the add button to add it to the selected menu on the right side.

Make sure the “LibreOffice Writer” is set as the scope and “Text” is set as the target.

Now, select the text, right-click, and start the macro from the context menu.

**Comment by OrionRandD** [comment]
On Thu, Jun 01, 2023 at 10:54:48AM -0700, iradraconis wrote:

-----------------
Thx a lot for replying...

-----------------

    Please select Extras -> Customize from the menu bar.

    Scroll down and select Context Menus.

    Scroll down the category and select Macros.

    Choose the macro from the list and click the add button to add it to
    the selected menu on the right side.

    Make sure the “LibreOffice Writer” is set as the scope and “Text” is
    set as the target.

    Now, select the text, right-click, and start the macro from the context
    menu.

    —
    Reply to this email directly, [1]view it on GitHub, or [2]unsubscribe.
    You are receiving this because you authored the thread. Message ID:
    ***@***.***
    m>

 References

    1. https://github.com/raniaamina/LibreOffice-Content-Generator/issues/2#issuecomment-1572531165

**Comment by raniaamina** [comment]
Sorry for late respons, yes @OrionRandD, you can add it in by costumize your menu as i did here
https://twitter.com/raniaamina_id/status/1635185145258086400

**Comment by OrionRandD** [comment]
> Sorry for late respons, yes @OrionRandD, you can add it in by costumize your menu as i did here https://twitter.com/raniaamina_id/status/1635185145258086400

Thx for replying :)
